services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "$PWD:/app"
    depends_on:
      - timescaledb
    # Dejar corriendo el contenedor
    command: tail -f /dev/null

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db
      DOCKER_INFLUXDB_INIT_USERNAME: johndoe
      DOCKER_INFLUXDB_INIT_PASSWORD: 1q2w3e4r5t6y
      DOCKER_INFLUXDB_INIT_ORG: org1
      DOCKER_INFLUXDB_INIT_BUCKET: bucket1
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: MpCpEGm1092T3PrbaUFGIRtadf1ggNMQx-IX55f_hLIYFG6E9JF9M3NdbnMlkpkT080YRkHgBoyWtIPAj_MJrQ==
    restart: always

volumes:
  timescaledb_data:
  influxdb_data: